# Generated by Django 4.2.3 on 2023-07-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.AddField(
            model_name='user',
            name='data',
            field=models.TextField(blank=True, max_length=2),
        ),
    ]
