# Generated by Django 4.2.3 on 2023-07-19 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_age_user_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='data',
        ),
    ]
